/* Shared Tailwind theme for all MVP screens (Obsidian / Stitch palette). Load after cdn.tailwindcss.com */
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#45dfa4",
        "inverse-on-surface": "#283044",
        "error-container": "#93000a",
        "surface-tint": "#7bd0ff",
        background: "#0b1326",
        "secondary-fixed": "#e1e0ff",
        "on-primary-container": "#004965",
        "surface-bright": "#31394d",
        "surface-container": "#171f33",
        surface: "#0b1326",
        "on-error": "#690005",
        "primary-fixed": "#c4e7ff",
        "on-background": "#dae2fd",
        "surface-container-lowest": "#060e20",
        "secondary-container": "#3131c0",
        primary: "#8ed5ff",
        "on-surface-variant": "#bdc8d1",
        "on-surface": "#dae2fd",
        "surface-container-highest": "#2d3449",
        "secondary-fixed-dim": "#c0c1ff",
        "tertiary-fixed": "#68fcbf",
        "on-tertiary-container": "#004e35",
        "on-secondary-fixed": "#07006c",
        "surface-dim": "#0b1326",
        "on-primary-fixed": "#001e2c",
        secondary: "#c0c1ff",
        "primary-container": "#38bdf8",
        error: "#ffb4ab",
        "on-primary-fixed-variant": "#004c69",
        "on-secondary-container": "#b0b2ff",
        "primary-fixed-dim": "#7bd0ff",
        "on-primary": "#00354a",
        "surface-variant": "#2d3449",
        "surface-container-high": "#222a3d",
        "tertiary-container": "#22c990",
        "on-secondary": "#1000a9",
        outline: "#87929a",
        "on-tertiary": "#003825",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#131b2e",
        "on-tertiary-fixed": "#002114",
        "on-tertiary-fixed-variant": "#005137",
        tertiary: "#4ee6aa",
        "on-secondary-fixed-variant": "#2f2ebe",
        "inverse-primary": "#00668a",
        "inverse-surface": "#dae2fd",
        "outline-variant": "#3e484f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
};
